# Generated by Django 6.0.5 on 2026-05-17 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('AYUDA', 'Se ayudan (Asociación benéfica)'), ('COMPITEN', 'Compiten (Asociación perjudicial)'), ('NEUTRA', 'Neutra')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Compatibilidades',
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ancho_terreno', models.FloatField(help_text='Ancho del terreno en metros')),
                ('largo_terreno', models.FloatField(help_text='Largo del terreno en metros')),
                ('distribucion_calculada', models.JSONField(help_text='Almacena el JSON de la matriz o posiciones calculadas')),
            ],
            options={
                'verbose_name_plural': 'Planificaciones',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distancia_minima_separacion', models.FloatField(help_text='Distancia en centímetros')),
                ('ph_optimo_suelo', models.FloatField(help_text='pH ideal')),
                ('necesidad_sol', models.CharField(choices=[('ALTA', 'Sol directo pleno'), ('MEDIA', 'Sombra parcial'), ('BAJA', 'Sombra total')], max_length=10)),
                ('compatibilidades', models.ManyToManyField(related_name='compatible_con', through='huerto.Compatibilidad', to='huerto.planta')),
            ],
        ),
        migrations.AddField(
            model_name='compatibilidad',
            name='planta_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_origen', to='huerto.planta'),
        ),
        migrations.AddField(
            model_name='compatibilidad',
            name='planta_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_destino', to='huerto.planta'),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilidad',
            unique_together={('planta_a', 'planta_b')},
        ),
    ]
