# Generated by Django 6.0.5 on 2026-05-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huerto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='plantas_solicitadas',
            field=models.JSONField(blank=True, help_text='Diccionario con las cantidades pedidas originalmente', null=True),
        ),
    ]
