# Generated by Django 6.0.5 on 2026-05-30 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huerto', '0003_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='nombre',
            field=models.CharField(default='Mi Huerto', max_length=150),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
